### ISSUE TITLE
Delay between clicking and opening of popup, add open event?

### ISSUE THREAD

**Issue by decay42** [tech-advantage/ngx-icon-picker#34]
There is a delay between clicking the input and the opening of the popup window, probably because of needing to load/render the icons.
Could you add an "afterOpen" event or something like that, which triggers once the popup is shown? That way one could implement a loading spinner as an indication of "something will happen soon".

**Comment by HerbertBodner** [comment]
This is exactly what I would need as well.

As an alternative, you might think of initializing the popup immediately, instead of initializing it when clicking on the input. (In that case you might want to add a switch to turn off that configuration, in case you have multiple controls on your page and initializing all of them would take a lot of resources and make the whole page non-interactive).

**Comment by greg7859** [comment]
I have little time to devote to this development in September. I won't be able to do anything before October.

**Comment by stanciupaul** [comment]
@greg7859 Any update on this?

**Comment by StanlyLife** [comment]
Update?

**Comment by greg7859** [comment]
I just publish a new release: 1.11.1

I added 3 outputs:
* (iconPickerOpen)           // On open popup
* (iconPickerClose)           // On close popup
* (iconPickerClose)           // On focus element

I modified an example to take in account the events and display an awaiting opening icon.
For more details, see:
* [app.component.ts](https://github.com/tech-advantage/ngx-icon-picker/blob/77ecc9b15ca7658252ef617ea4ecf2ec19d1d31c/projects/app/src/app/app.component.ts#L92)
* [app.component.html](https://github.com/tech-advantage/ngx-icon-picker/blob/77ecc9b15ca7658252ef617ea4ecf2ec19d1d31c/projects/app/src/app/app.component.html#L22)
