### ISSUE TITLE
Generic type 'ɵɵComponentDeclaration' requires between 7 and 8 type arguments.

### ISSUE THREAD

**Issue by joharzmn** [tech-advantage/ngx-icon-picker#70]
Version: 1.10.0

Angular Version: 14.3.2

![image](https://user-images.githubusercontent.com/16515522/208936705-a58a5495-a010-401d-ae7c-da16f9558b6f.png)

**Comment by michaelmarcuccio** [comment]
There is no angular version 14.3.2

**Comment by DLazorenkoNteract** [comment]
![image](https://user-images.githubusercontent.com/71394022/210332332-aaa8fe43-ecac-4a98-b93a-30e27e1529ec.png)
Have the same error in Azure pipeline (builds fine locally)

**Comment by michaelmarcuccio** [comment]
This probably won't be looked into until someone who runs into the error gives information such as actual Angular version.

**Comment by DLazorenkoNteract** [comment]
> This probably won't be looked into until someone who runs into the error gives information such as actual Angular version.

Angular: 14.2.12
ngx-icon-picker: 1.10.0 - error, 1.9.1 works fine.

**Comment by michaelmarcuccio** [comment]
I am able to reproduce this issue with a new Angular project v14 and ngx-icon-picker v1.10.0.
For some reason when 'preparing' ngx-icon-picker locally and 'npm link' into the Angular v14 project instead of using the v1.10.0 npm package, I don't get the build errors. @greg7859 any idea as to why this would occur?
